/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "mock_chain.h"
#include <stdio.h>
#include <string.h>
#include "utils.h"
#include "sha1.h"

int get_transaction_id_client(CLIENT* clnt) {
	
	int* result;

	result = get_transaction_id_100(NULL, clnt);
	if (result == NULL) {
		printf("Error on RPC call 'get_transaction_id'\n");
		exit(0);
	}

	return *result;
}

int get_challenge_client(CLIENT* clnt, int transaction_id) {
	int* result;
	int* t_id = &transaction_id;

	result = get_challenge_100(t_id, clnt);
	if (result == NULL) {
		printf("Error on RPC call 'get_challenge'\n");
		exit(0);
	}

	return *result;
}

int get_transaction_status_client(CLIENT* clnt, int transaction_id) {
	int* result;
	int* t_id = &transaction_id;

	result = get_transaction_status_100(t_id, clnt);
	if (result == NULL) {
		printf("Error on RPC call 'get_transaction_status'\n");
		exit(0);
	}

	return *result;
}

int get_winner_client(CLIENT* clnt, int transaction_id) {
	int* result;
	int* t_id = &transaction_id;

	result = get_winner_100(t_id, clnt);
	if (result == NULL) {
		printf("Error on RPC call 'get_winner'\n");
		exit(0);
	}

	return *result;
}

status_t get_seed_client(CLIENT* clnt, int transaction_id) {
	status_t* result;
	int* t_id = &transaction_id;

	result = get_seed_100(t_id, clnt);
	if (result == NULL) {
		printf("Error on RPC call 'get_winner'\n");
		exit(0);
	}

	return *result;
}

int mine_client(CLIENT* clnt) {
	int transaction_id = get_transaction_id_client(clnt);
	int challenge = get_challenge_client(clnt, transaction_id);

	unsigned char mask[20] = {0};
	create_mask(mask, challenge);

	unsigned char hashed[20] = {0};
	int res = 0;
	int seed = 0;
	while (res == 0) {
		sha1digest(hashed, NULL, (uint8_t*)(&seed), sizeof(seed));
		if (and_mask(hashed, mask, 20)) {
			submission_t submission = {
				transaction_id,
				1,
				seed
			};
			printf("Submitting seed %d...\n", seed);
			res = *submit_challenge_100(&submission, clnt);
		}
		seed++;
	}
	
}


int main (int argc, char *argv[]) {
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	CLIENT* clnt = clnt_create(argv[1], mock_chain, v, "udp");
	/* Garantindo a criacao da ligacao com o remoto */
	if (clnt == (CLIENT *) NULL) {
		clnt_pcreateerror(argv[1]);
		exit(1);
	}

	char command[100];

	printf("\n1 - getTransactionID: gets the current transaction id from the server\n"
		   "\n2 - getChallenge <transactionID>: gets the challenge related to given transaction id\n"
		   "\n3 - getTransactionStatus <transactionID>: gets the status of the given transaction id\n"
		   "\n4 - getWinner <transactionID>: gets the winner of the transaction\n"
		   "\n5 - getSeed <transactionID>: gets the seed for the given transaction id if the transaction was already won\n"
		   "\n6 - mine: looks for the seed related to the current transaction\n"
		   "\n7 - exit: exit client\n");

	while (1) {
		scanf("%s", command);

		if 		(!strcmp(command, "getTransactionID") || !strcmp(command, "1")) {
			int transaction_id = get_transaction_id_client(clnt);
			printf("%d\n", transaction_id);
		}

		else if (!strcmp(command, "getChallenge") || !strcmp(command, "2")) {
			int transaction_id;
			scanf("%d", &transaction_id);

			int challenge = get_challenge_client(clnt, transaction_id);
			printf("%d\n", challenge);
		}

		else if (!strcmp(command, "getTransactionStatus") || !strcmp(command, "3")) {
			int transaction_id;
			scanf("%d", &transaction_id);

			int status = get_transaction_status_client(clnt, transaction_id);
			printf("%d\n", status);
		}

		else if (!strcmp(command, "getWinner") || !strcmp(command, "4")) {
			int transaction_id;
			scanf("%d", &transaction_id);

			int winner = get_winner_client(clnt, transaction_id);
			printf("%d\n", winner);
		}

		else if (!strcmp(command, "getSeed") || !strcmp(command, "5")) {
			int transaction_id;
			scanf("%d", &transaction_id);

			status_t status = get_seed_client(clnt, transaction_id);
			if (status.status == 0) {
				printf("%d\n", status.seed);
			}
		}

		else if (!strcmp(command, "mine") || !strcmp(command, "6")) {
			mine_client(clnt);
		}

		else if (!strcmp(command, "exit") || !strcmp(command, "7")) {
			return 0;
		}

		else {
			printf("Unknown command\n");
		}

	}
	

}
