/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mock_chain.h"

bool_t
xdr_submission_t (XDR *xdrs, submission_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->transaction_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->client_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seed))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_status_t (XDR *xdrs, status_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seed))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->challenge))
		 return FALSE;
	return TRUE;
}
